#
# This file contains configuration flags to customize the site
#

# Site settings
# Name of your site (displayed in the header)
name: 'Example Vacuum Theme'
title: "Example: What is the title of your site?"

# Short bio or description (displayed in the header)
description: "Lorem Ipsum something about your site and you too probably."
timezone: America\New_York

# Creator settings
creator: 'Example Author Name'
# URL of your avatar or profile pic (you could use your GitHub profile pic)
#  '/theme/images/avatar.jpg'

# Icon settings
logo: https://avatars3.githubusercontent.com/u/9919?v=3&s=200
logo_description: 'This is my avatar'
favicon: images/site-icons/favicon.ico

# Build Settings
## Conversion
markdown: kramdown
highlighter: coderay #or rouge
#lsi: true // Boolean to determine to produce an index for related posts.
theme: vacuum-jekyll-theme

## Where things are
source: ./static
destination: ./_site
layouts_dir: templates

## Handling Reading
safe: false
encoding: "utf-8"
# Exclude these files from your production _site
exclude: [vendor]
#include:
#keep_files:

## Filtering Content
limit_posts: 4
future: false
unpublished: false
permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # Minified using :compressed, other choice is :expanded

# Build Plugins
whitelist: []
#gems:

# Serve settings
detach: false
host: localhost
port: 4831

# Your website URL (e.g. http://user.github.io)
# Used for Sitemap.xml and your RSS feed
url: "http://www.example.com" # the base hostname & protocol for your site
# If hosting site at a Project repository on GitHub pages
# (http://username.github.io/repository-name)
# and NOT the User repository (http://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "" # the subpath of the site, e.g. /blog/

# Front Matter Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: {{ site.creator}}

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

excerpt_separator: ""
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: true
  input: GFM

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style


# About Page Info
about_page_header: "About Page Header"
center_image: "images/image.jpg"

#
# Flags below are optional
#

# List of links for navigation
navigation: [
    # You probably want to fill these in so they point to your user pages
    {'site': 'flickr', 'user': '', 'url': 'http://www.flickr.com/...'},
    {'site': 'github', 'user': '', 'url': 'https://github.com/...'},
    {'site': 'google-plus', 'user': '', 'url': 'https://plus.google.com/...'},
    {'site': 'instagram', 'user': '', 'url': 'http://www.instagram.com/user/...'},
    {'site': 'lastfm', 'user': '', 'url': 'http://www.last.fm/user/...'},
    {'site': 'linkedin', 'user': '', 'url': 'http://linkedin.com/in/...'},
    {'site': 'pinterest', 'user': '', 'url': 'http://www.pinterest.com/...'},
    {'site': 'spotify', 'user': '', 'url': 'https://open.spotify.com/user/...'},
    {'site': 'stackoverflow', 'user': '', 'url': 'http://www.stackoverflow.com/user/...'},
    {'site': 'twitter', 'user': '', 'url': 'https://twitter.com/...'}
]

show_social:
  facebook: false
  twitter: false

# TODO Includes an icon in the footer for each username you enter
footer-links:
#  email: "example@mail.net"
#  facebook_id:
#  flickr_id:
#  github_id:
#  instagram_id:
#  linkedin_url:
#  pinterest_id:
#  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
#  stackoverflow_url: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
#  twitter_id:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
#disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics:

# Feed Settings
feed:
  main: /feed/feed.xml
  # TODO Ensure tag feed works properly
  tag:  /feed/tag/%s.atom.xml
